### ISSUE TITLE
encoding problems

### ISSUE THREAD

**Issue by DeathError** [sqshq/sampler#43] opened 2019-08-19 05:51 UTC
I am using WSL (https://docs.microsoft.com/en-us/windows/wsl/install-win10) Debian GNU/Linux and I'm having problems with the encoding
**/etc/default/locale:**
```
#  File generated by update-locale
LC_ALL=C
LANGUAGE=en_US.UTF-8
```

**/etc/default/keyboard:**
``` # KEYBOARD CONFIGURATION FILE

# Consult the keyboard(5) manual page.

XKBMODEL="pc105"
XKBLAYOUT="us"
XKBVARIANT="rus"
XKBOPTIONS=""

BACKSPACE="guess"
```

![image](https://user-images.githubusercontent.com/6966058/63241620-0f8a9c00-c25d-11e9-84e9-11f8082e7a7f.png)

**Comment by sqshq** [comment] 2019-08-20 02:37
Hi @DeathError,
Please take a look at the similar discussion: https://github.com/sqshq/sampler/issues/33

**Comment by sqshq** [comment] 2019-08-24 02:03
Closing as a duplicate (also the issue is on WSL side)

**Closed by sqshq** 2019-08-24 02:03 UTC
